//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIUSchoolSystem.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long Id { get; set; }
        public string ShortMessage { get; set; }
        public string FullMessage { get; set; }
        public string IpAddress { get; set; }
        public Nullable<long> UserId { get; set; }
        public string PageUrl { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> CreatedByUserId { get; set; }
        public Nullable<long> LastUpdatedByUserId { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    }
}
