//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIUSchoolSystem.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailLog
    {
        public long Id { get; set; }
        public Nullable<long> TenantId { get; set; }
        public string MailFrom { get; set; }
        public string MailTo { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string Bcc { get; set; }
        public string Cc { get; set; }
        public int Type { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> CreatedByUserId { get; set; }
        public Nullable<long> LastUpdatedByUserId { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    }
}
