//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIUSchoolSystem.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.Users = new HashSet<User>();
            this.PermissionRecords = new HashSet<PermissionRecord>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> CreatedByUserId { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public Nullable<long> LastUpdatedByUserId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<PermissionRecord> PermissionRecords { get; set; }
    }
}
