//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIUSchoolSystem.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string SettingName { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
        public Nullable<long> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> LastUpdatedByUserId { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    }
}
